import Link from "next/link";
import { Brain } from "@/components/Pixel";

const BASE = (process.env.NEXT_PUBLIC_BASE_PATH || "").replace(/^\/$/, "").replace(/\/$/, "");
const REPO = process.env.NEXT_PUBLIC_REPO_URL || "";

export default function AboutPage() {
  return (
    <main>
      <p className="dateline">About</p>
      <h1>A maintenance log for skills, with a bouncer at the door.</h1>
      <p className="lede">
        People are handing more of their thinking to AI, and the research says the loss is real, domain-specific, and invisible from the inside. Fallow keeps a ledger of what you hand over, models how each skill
        fades when you stop using it, and pushes back at the moment you are about to delegate something that keeps you sharp.
      </p>

      <section className="section">
        <p className="section-label">The loop</p>
        <p>
          <b>Every ask gets filed.</b> A prompt typed into ChatGPT, Claude or Gemini, a prompt in Claude Code, or a line pasted into the Gate is classified three ways: which cognitive domain it belongs to
          (composition, analytical reasoning, quantitative, recall, synthesis, navigation, planning, ideation, implementation, verbal), what kind of ask it is (answer, hint, review, explain), and how much of the
          work you brought yourself. Asking for the finished thing counts as delegation. Bringing a draft, asking for a hint, or asking for an explanation counts as practice. That split is the whole game, because in
          every learning study the answer-askers lose ground and the hint-askers do not.
        </p>
        <p>
          <b>Every domain is a flashcard.</b> Each one carries a stability, the number of days until the model expects it to fade to 90%. Doing the work yourself is a review: stability grows, and grows more if the
          domain was already stale. Handing it to AI is not a review. Time runs. A domain nobody has worked in three months reads &ldquo;stale&rdquo;, and one real session roughly doubles its stability, so the nudges
          for skills you keep up thin out on their own.
        </p>
        <p>
          <b>The verdict comes before the answer.</b> When you are about to delegate, the policy weighs how stale the domain is, whether you put it on your keep list, whether the task is conceptual or rote, how much
          capacity you have left today, and whether there is a real deadline. It returns one of four modes: do it yourself, scaffold, co-pilot, or delegate. In a chat window that is a card with three buttons; in
          Claude Code it is a line of context the model follows.
        </p>
        <p>
          <b>Capacity is sleep pressure, not dopamine.</b> The Day page draws today&rsquo;s alertness from the three-process model used in aviation and the US Army, from nothing more than your bed and wake times.
          Low capacity is a reason to delegate, not a reason to push.
        </p>
        <p>
          <b>Screens get a pause, not a lock.</b> On the sites you list, the extension puts a short breath before the page loads, with your own daily budget shown on it. That is the one screen-time intervention
          with clean field evidence. Locks work for a few weeks and then get removed.
        </p>
      </section>

      <section className="section">
        <p className="section-label">The creature</p>
        <div className="two-col">
          <div>
            <p>
              The brain on the field board is a reading of the ledger, not a mascot with a mood dial. Its health is 70% the mean retrievability of your keep list, 20% the share of the last thirty days&rsquo;
              asks you did or shared, and 10% today&rsquo;s capacity. Thriving from 80, steady from 60, fading from 40, fallow below. If delegation is rising on a keep-list domain, it drops a stage for the
              week, so it reacts to the trend before the numbers do.
            </p>
            <p>
              Four stages, four drawings each, and the whole thing is code: a 32 by 32 grid of palette keys per frame, generated by a short Python script in <code>scripts/pixel</code> and drawn on a canvas at
              an integer scale. No image files, so the creature and the plot tiles can change with the data without anyone redrawing them. The feet, the mouth and the gloss all got cut; the eyes carry it.
            </p>
          </div>
          <div style={{ display: "grid", gap: 8, alignContent: "start" }}>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 6 }}>
              {(["thriving", "steady", "fading", "fallow"] as const).map((s) => (
                <div key={s} style={{ textAlign: "center" }}>
                  <Brain stage={s} scale={3} ground={false} />
                  <div className="small" style={{ textTransform: "capitalize" }}>{s}</div>
                </div>
              ))}
            </div>
            <p className="small">Same creature, four readings. The hosted demo ledger usually lands on steady.</p>
          </div>
        </div>
      </section>

      <section className="section">
        <p className="section-label">The extension</p>
        <div className="two-col">
          <div>
            <img src={`${BASE}/img/extension-card.png`} alt="The verdict card over a chat window" style={{ width: "100%", border: "2px solid var(--ink)" }} />
            <p className="small">The card over a chat composer: mode, reasons, the scaffold, and three choices. &ldquo;I&rsquo;ll try first&rdquo; starts a 15-minute timer and logs the attempt.</p>
          </div>
          <div>
            <img src={`${BASE}/img/extension-pause.png`} alt="The pause before an entertainment site opens" style={{ width: "100%", border: "2px solid var(--ink)" }} />
            <p className="small">The pause before a listed site opens: a countdown, how many times today, minutes against your budget. Continue unlocks when the count ends.</p>
          </div>
        </div>
        <p className="small" style={{ marginTop: 12 }}>
          You can try the card without installing anything on the <Link href="/demo/chat" style={{ textDecoration: "underline" }}>demo chat page</Link>.
        </p>
      </section>

      <section className="section">
        <p className="section-label">Where the data comes from</p>
        <p>
          Nothing syncs from anyone&rsquo;s account; there is no API for that. Three doors in: the browser extension files asks as they are typed; a ChatGPT or Claude data export, dropped on the Import page,
          fills in months of history (parsed in the browser, never uploaded); and hooks for Claude Code and Cursor file terminal prompts. ActivityWatch, an open-source local time tracker, supplies the
          attention numbers if you run it.
        </p>
        <p>
          This hosted version keeps the whole ledger in your browser&rsquo;s own storage. The self-hosted version keeps it in one file on your machine. Neither has accounts or a server that sees your prompts.
        </p>
      </section>

      <section className="section">
        <p className="section-label">What it does not claim</p>
        <p>
          Fallow measures asks, not ability. It does not measure your brain, diagnose anything, predict disease, or &ldquo;train&rdquo; regions; the brain notes on the field board are group-average imaging results
          phrased as engagement, because reverse inference from region to process is weak. Stability priors, the fatigue penalty and the policy thresholds are borrowed from the literature or guessed, and the code
          says so. Whether a domain the model calls stale predicts a real drop on an unassisted task is the first study to run, and nobody has run it.
        </p>
      </section>

      <section className="section">
        <p className="section-label">Built with</p>
        <p className="small">
          TypeScript, Next.js 15, React 19, hand-drawn SVG, pixel art generated from Python grids, Pixelify Sans, a lexicon classifier, an FSRS-style scheduler, the three-process alertness model, a Manifest
          V3 extension, ActivityWatch&rsquo;s REST API, vitest and Playwright. The research behind each piece is on the <Link href="/evidence" style={{ textDecoration: "underline" }}>Evidence</Link> page.
          {REPO && (
            <>
              {" "}
              Source and setup: <a href={REPO} style={{ textDecoration: "underline" }}>{REPO.replace(/^https?:\/\//, "")}</a>.
            </>
          )}
        </p>
      </section>
    </main>
  );
}
