// Generated by scripts/build-extension.mjs from src/core. Do not edit by hand.

// src/core/alertness.ts
var LOWER_ASYMPTOTE = 2.4;
var UPPER_ASYMPTOTE = 14.3;
var WAKE_DECAY = 0.0353;
var SLEEP_RECOVERY = 0.381;
var C_AMPLITUDE = 2.5;
var C_PHASE_DEFAULT = 16.8;
var U_AMPLITUDE = 0.5;
var U_MESOR = -0.5;
var W_START = -5.72;
var W_DECAY = 1.51;
var KSS_A = 9.68;
var KSS_B = 0.46;
var CHRONOTYPE_SHIFT = {
  morning: -1.3,
  intermediate: 0,
  evening: 0.7
};
function parseClock(hhmm) {
  const m = /^(\d{1,2}):(\d{2})$/.exec(hhmm.trim());
  if (!m) throw new Error(`Bad clock time: ${hhmm}`);
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (h < 0 || h > 23 || min < 0 || min > 59) throw new Error(`Bad clock time: ${hhmm}`);
  return h + min / 60;
}
function wakeHours(sleep) {
  const bed = parseClock(sleep.bed);
  const wake = parseClock(sleep.wake);
  const awake = ((bed - wake) % 24 + 24) % 24;
  return awake === 0 ? 24 : awake;
}
function isAsleep(h, sleep) {
  const bed = parseClock(sleep.bed);
  const wake = parseClock(sleep.wake);
  const x = (h % 24 + 24) % 24;
  if (bed > wake) return x >= bed || x < wake;
  return x >= bed && x < wake;
}
function steadyStateWakeLevel(sleep) {
  const awake = wakeHours(sleep);
  const asleep = 24 - awake;
  let sw = UPPER_ASYMPTOTE;
  for (let i = 0; i < 40; i++) {
    const ss = LOWER_ASYMPTOTE + (sw - LOWER_ASYMPTOTE) * Math.exp(-WAKE_DECAY * awake);
    sw = UPPER_ASYMPTOTE - (UPPER_ASYMPTOTE - ss) * Math.exp(-SLEEP_RECOVERY * asleep);
  }
  return sw;
}
function circadian(h, chronotype = "intermediate") {
  const p = C_PHASE_DEFAULT + CHRONOTYPE_SHIFT[chronotype];
  return C_AMPLITUDE * Math.cos(2 * Math.PI * (h - p) / 24);
}
function ultradian(h) {
  return U_AMPLITUDE * Math.cos(2 * Math.PI * h / 12) + U_MESOR;
}
function kssFromAlertness(a) {
  return Math.min(9, Math.max(1, KSS_A - KSS_B * a));
}
function alertnessAt(h, sleep, chronotype = "intermediate") {
  const wake = parseClock(sleep.wake);
  const bed = parseClock(sleep.bed);
  const sw = steadyStateWakeLevel(sleep);
  const awakeHours = wakeHours(sleep);
  const x = (h % 24 + 24) % 24;
  const asleep = isAsleep(x, sleep);
  let S;
  let W = 0;
  if (!asleep) {
    const tAwake = ((x - wake) % 24 + 24) % 24;
    S = LOWER_ASYMPTOTE + (sw - LOWER_ASYMPTOTE) * Math.exp(-WAKE_DECAY * tAwake);
    W = W_START * Math.exp(-W_DECAY * tAwake);
  } else {
    const ss = LOWER_ASYMPTOTE + (sw - LOWER_ASYMPTOTE) * Math.exp(-WAKE_DECAY * awakeHours);
    const tAsleep = ((x - bed) % 24 + 24) % 24;
    S = UPPER_ASYMPTOTE - (UPPER_ASYMPTOTE - ss) * Math.exp(-SLEEP_RECOVERY * tAsleep);
  }
  const C = circadian(x, chronotype);
  const U = ultradian(x);
  const alertness = S + C + U + W;
  return { h: x, S: r2(S), C: r2(C), U: r2(U), W: r2(W), alertness: r2(alertness), kss: r2(kssFromAlertness(alertness)), asleep };
}
function dayCurve(sleep, chronotype = "intermediate", stepMinutes = 30) {
  const out = [];
  for (let m = 0; m <= 24 * 60; m += stepMinutes) out.push(alertnessAt(m / 60, sleep, chronotype));
  return out;
}
var FATIGUE_TAU_MIN = 120;
var FATIGUE_FULL_MIN = 360;
function fatigueLevel(events, now = /* @__PURE__ */ new Date()) {
  const nowMs = now.getTime();
  const dayStart = nowMs - 18 * 36e5;
  let f = 0;
  for (const e of events) {
    if (!e.demanding || !e.minutes) continue;
    const t = Date.parse(e.ts);
    if (t < dayStart || t > nowMs) continue;
    const endMs = t + e.minutes * 6e4;
    const restMin = Math.max(0, (nowMs - endMs) / 6e4);
    f += e.minutes / FATIGUE_FULL_MIN * Math.exp(-restMin / FATIGUE_TAU_MIN);
  }
  return Math.min(1, f);
}
var FATIGUE_PENALTY = 0.35;
function capacityAt(now, sleep, chronotype, events) {
  const h = now.getHours() + now.getMinutes() / 60;
  const a = alertnessAt(h, sleep, chronotype);
  const fatigue = fatigueLevel(events, now);
  const base = Math.min(1, Math.max(0, (a.alertness - 1) / 15));
  const value = a.asleep ? 0 : r2(base * (1 - FATIGUE_PENALTY * fatigue));
  return { value, alertness: a.alertness, kss: a.kss, fatigue: r2(fatigue), asleep: a.asleep };
}
function r2(n) {
  return Math.round(n * 100) / 100;
}

// src/core/taxonomy.ts
var STABILITY_BY_CLASS = {
  fast: 14,
  medium: 30,
  slow: 60,
  none: Number.POSITIVE_INFINITY
};
var DOMAINS = [
  {
    id: "composition",
    label: "Composition",
    short: "Drafting prose and argument",
    chc: "Grw, Gc",
    onet: ["Written Expression", "Originality"],
    examples: ["emails", "essays", "docs", "cover letters", "posts"],
    typicalAsk: "write me",
    engages: "left inferior frontal and temporal language network (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Write the first full draft of your next email or doc yourself, then ask for a critique.",
    lexicon: [
      { term: "write", weight: 1 },
      { term: "draft", weight: 1.2 },
      { term: "rewrite", weight: 0.8 },
      { term: "compose", weight: 1.2 },
      { term: "essay", weight: 1.3 },
      { term: "email", weight: 1 },
      { term: "cover letter", weight: 1.5 },
      { term: "paragraph", weight: 1 },
      { term: "blog", weight: 1 },
      { term: "post", weight: 0.5 },
      { term: "caption", weight: 0.8 },
      { term: "bio", weight: 0.8 },
      { term: "statement", weight: 0.8 },
      { term: "proofread", weight: 0.6 },
      { term: "tone", weight: 0.6 },
      { term: "wording", weight: 0.8 },
      { term: "phrase", weight: 0.6 },
      { term: "letter", weight: 0.7 },
      { term: "memo", weight: 1 },
      { term: "abstract", weight: 0.7 },
      { term: "intro", weight: 0.5 },
      { term: "conclusion", weight: 0.5 }
    ]
  },
  {
    id: "analysis",
    label: "Analytical reasoning",
    short: "Debugging, diagnosing, proving",
    chc: "Gf",
    onet: ["Deductive Reasoning", "Inductive Reasoning", "Problem Sensitivity"],
    examples: ["debugging", "diagnosing failures", "proofs", "root-cause work"],
    typicalAsk: "why doesn't this work",
    engages: "multiple-demand network, lateral prefrontal and parietal (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Before pasting the error, write down two hypotheses and test the cheaper one.",
    lexicon: [
      { term: "why", weight: 0.8 },
      { term: "why doesn't", weight: 1.5 },
      { term: "why does", weight: 1.2 },
      { term: "why isn't", weight: 1.5 },
      { term: "why won't", weight: 1.5 },
      { term: "why did", weight: 1.2 },
      { term: "debug", weight: 1.5 },
      { term: "bug", weight: 1.2 },
      { term: "error", weight: 1 },
      { term: "fails", weight: 0.8 },
      { term: "failing", weight: 0.8 },
      { term: "broken", weight: 0.8 },
      { term: "doesn't work", weight: 1.2 },
      { term: "does not work", weight: 1.2 },
      { term: "not working", weight: 1.2 },
      { term: "fix", weight: 0.9 },
      { term: "diagnose", weight: 1.3 },
      { term: "root cause", weight: 1.4 },
      { term: "prove", weight: 1.2 },
      { term: "proof", weight: 1.2 },
      { term: "logic", weight: 0.8 },
      { term: "reason", weight: 0.6 },
      { term: "stack trace", weight: 1.4 },
      { term: "traceback", weight: 1.4 },
      { term: "exception", weight: 1 },
      { term: "undefined", weight: 0.7 },
      { term: "null", weight: 0.5 },
      { term: "wrong", weight: 0.6 },
      { term: "compare", weight: 0.5 },
      { term: "evaluate", weight: 0.6 },
      { term: "tradeoff", weight: 0.8 },
      { term: "trade-off", weight: 0.8 }
    ]
  },
  {
    id: "quantitative",
    label: "Quantitative reasoning",
    short: "Math, estimation, statistics",
    chc: "Gq, Gf",
    onet: ["Mathematical Reasoning", "Number Facility"],
    examples: ["mental math", "unit conversions", "statistics", "back-of-envelope estimates"],
    typicalAsk: "calculate",
    engages: "bilateral intraparietal sulcus (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Estimate the answer to one significant figure before you compute it.",
    lexicon: [
      { term: "calculate", weight: 1.5 },
      { term: "compute", weight: 1 },
      { term: "math", weight: 1.3 },
      { term: "equation", weight: 1.2 },
      { term: "formula", weight: 1 },
      { term: "percent", weight: 0.9 },
      { term: "%", weight: 0.6 },
      { term: "average", weight: 0.8 },
      { term: "mean", weight: 0.5 },
      { term: "median", weight: 0.9 },
      { term: "probability", weight: 1.2 },
      { term: "statistic", weight: 1.2 },
      { term: "regression", weight: 1 },
      { term: "derivative", weight: 1.3 },
      { term: "integral", weight: 1.3 },
      { term: "solve for", weight: 1.3 },
      { term: "convert", weight: 0.7 },
      { term: "estimate", weight: 0.9 },
      { term: "how many", weight: 0.8 },
      { term: "how much", weight: 0.7 },
      { term: "budget", weight: 0.6 },
      { term: "interest rate", weight: 1 },
      { term: "p-value", weight: 1.3 },
      { term: "standard deviation", weight: 1.3 },
      { term: "sum", weight: 0.6 },
      { term: "total", weight: 0.4 }
    ]
  },
  {
    id: "recall",
    label: "Recall",
    short: "Names, facts, APIs, vocabulary",
    chc: "Gl, Gr",
    onet: ["Memorization"],
    examples: ["a function signature", "a date", "a word in another language", "who said what"],
    typicalAsk: "what is the",
    engages: "hippocampus and medial temporal lobe (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Guess first. Say the answer out loud, then check it.",
    lexicon: [
      { term: "what is the", weight: 0.9 },
      { term: "what's the", weight: 0.9 },
      { term: "what was", weight: 0.7 },
      { term: "who is", weight: 0.8 },
      { term: "who was", weight: 0.8 },
      { term: "when did", weight: 0.9 },
      { term: "when was", weight: 0.9 },
      { term: "remind me", weight: 1.3 },
      { term: "name of", weight: 1.1 },
      { term: "called", weight: 0.5 },
      { term: "definition", weight: 1 },
      { term: "define", weight: 1 },
      { term: "meaning of", weight: 1 },
      { term: "syntax for", weight: 1.2 },
      { term: "syntax", weight: 0.7 },
      { term: "capital of", weight: 1.2 },
      { term: "date of", weight: 0.9 },
      { term: "translate", weight: 0.9 },
      { term: "in spanish", weight: 0.8 },
      { term: "in french", weight: 0.8 },
      { term: "acronym", weight: 1 },
      { term: "stand for", weight: 1 },
      { term: "which command", weight: 1 },
      { term: "flag for", weight: 0.9 },
      { term: "shortcut", weight: 0.9 }
    ]
  },
  {
    id: "synthesis",
    label: "Reading and synthesis",
    short: "Reading closely, summarizing, connecting",
    chc: "Grw, Gc",
    onet: ["Written Comprehension", "Information Ordering"],
    examples: ["papers", "long threads", "contracts", "meeting notes"],
    typicalAsk: "summarize this",
    engages: "language network with default-mode regions (group-average)",
    decayClass: "medium",
    stabilityPrior: STABILITY_BY_CLASS.medium,
    practice: "Read the abstract and the figures, write a three-sentence summary, then compare.",
    lexicon: [
      { term: "summarize", weight: 1.6 },
      { term: "summary", weight: 1.4 },
      { term: "summarise", weight: 1.6 },
      { term: "tl;dr", weight: 1.6 },
      { term: "tldr", weight: 1.6 },
      { term: "key points", weight: 1.3 },
      { term: "main points", weight: 1.3 },
      { term: "takeaways", weight: 1.3 },
      { term: "this paper", weight: 1 },
      { term: "this article", weight: 1 },
      { term: "this document", weight: 0.9 },
      { term: "this thread", weight: 0.9 },
      { term: "read this", weight: 1 },
      { term: "what does this say", weight: 1.2 },
      { term: "in simple terms", weight: 0.8 },
      { term: "eli5", weight: 1 },
      { term: "overview", weight: 0.8 },
      { term: "digest", weight: 0.9 },
      { term: "notes on", weight: 0.8 },
      { term: "literature", weight: 0.8 },
      { term: "sources", weight: 0.5 },
      { term: "explain this", weight: 0.9 }
    ]
  },
  {
    id: "navigation",
    label: "Spatial navigation",
    short: "Wayfinding, layouts, mental rotation",
    chc: "Gv",
    onet: ["Spatial Orientation", "Visualization"],
    examples: ["routes without GPS", "room layouts", "maps", "mental rotation"],
    typicalAsk: "how do I get to",
    engages: "hippocampus, entorhinal cortex, retrosplenial cortex (group-average)",
    decayClass: "medium",
    stabilityPrior: STABILITY_BY_CLASS.medium,
    practice: "Look at the map once, put the phone away, and navigate the last ten minutes from memory.",
    lexicon: [
      { term: "directions", weight: 1.5 },
      { term: "route to", weight: 1.3 },
      { term: "the route", weight: 1.1 },
      { term: "fastest route", weight: 1.4 },
      { term: "best route", weight: 1.4 },
      { term: "walking route", weight: 1.4 },
      { term: "driving route", weight: 1.4 },
      { term: "how do i get to", weight: 1.5 },
      { term: "how to get to", weight: 1.5 },
      { term: "map of", weight: 1.2 },
      { term: "the map", weight: 1 },
      { term: "a map", weight: 1 },
      { term: "google maps", weight: 1.3 },
      { term: "apple maps", weight: 1.3 },
      { term: "nearest", weight: 0.9 },
      { term: "navigate", weight: 1.3 },
      { term: "layout", weight: 0.9 },
      { term: "floor plan", weight: 1.3 },
      { term: "spatial", weight: 1 },
      { term: "rotate", weight: 0.7 },
      { term: "north", weight: 0.6 },
      { term: "distance from", weight: 0.9 },
      { term: "which way", weight: 1 },
      { term: "walk from", weight: 1 },
      { term: "drive from", weight: 1 },
      { term: "where is", weight: 0.8 }
    ]
  },
  {
    id: "planning",
    label: "Planning",
    short: "Scheduling, sequencing, decomposing",
    chc: "Executive updating and shifting",
    onet: ["Information Ordering", "Time Sharing"],
    examples: ["study plans", "project breakdowns", "trip itineraries", "sprint plans"],
    typicalAsk: "make me a plan",
    engages: "frontoparietal control network (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Sketch the plan in five lines on paper first, then ask what you missed.",
    lexicon: [
      { term: "plan", weight: 1.3 },
      { term: "schedule", weight: 1.3 },
      { term: "roadmap", weight: 1.3 },
      { term: "timeline", weight: 1 },
      { term: "itinerary", weight: 1.4 },
      { term: "break down", weight: 1.1 },
      { term: "breakdown", weight: 1 },
      { term: "steps to", weight: 1 },
      { term: "step by step", weight: 0.8 },
      { term: "prioritize", weight: 1.2 },
      { term: "prioritise", weight: 1.2 },
      { term: "organize", weight: 1 },
      { term: "organise", weight: 1 },
      { term: "milestones", weight: 1.2 },
      { term: "todo", weight: 0.9 },
      { term: "to-do", weight: 0.9 },
      { term: "checklist", weight: 0.9 },
      { term: "agenda", weight: 1 },
      { term: "sprint", weight: 0.9 },
      { term: "deadline", weight: 0.7 },
      { term: "this week", weight: 0.5 },
      { term: "study plan", weight: 1.5 }
    ]
  },
  {
    id: "ideation",
    label: "Creative ideation",
    short: "Brainstorming, naming, concepts",
    chc: "Gr fluency",
    onet: ["Fluency of Ideas", "Originality"],
    examples: ["project ideas", "names", "titles", "design concepts", "angles for a piece"],
    typicalAsk: "give me ten ideas",
    engages: "default-mode and control network coupling (group-average)",
    decayClass: "medium",
    stabilityPrior: STABILITY_BY_CLASS.medium,
    practice: "List ten of your own before asking; only then ask for ten more and mark which are yours.",
    lexicon: [
      { term: "ideas", weight: 1.5 },
      { term: "idea", weight: 0.9 },
      { term: "brainstorm", weight: 1.6 },
      { term: "suggest", weight: 0.8 },
      { term: "suggestions", weight: 0.9 },
      { term: "names for", weight: 1.4 },
      { term: "name for", weight: 1.3 },
      { term: "title for", weight: 1.3 },
      { term: "titles", weight: 1 },
      { term: "creative", weight: 1 },
      { term: "concept", weight: 0.8 },
      { term: "angles", weight: 0.9 },
      { term: "options for", weight: 0.8 },
      { term: "alternatives", weight: 0.8 },
      { term: "what could i", weight: 0.8 },
      { term: "come up with", weight: 1.2 },
      { term: "pitch", weight: 0.8 },
      { term: "slogan", weight: 1.2 },
      { term: "tagline", weight: 1.2 },
      { term: "theme", weight: 0.6 }
    ]
  },
  {
    id: "implementation",
    label: "Implementation",
    short: "Turning intent into code, formulas, config",
    chc: "Gkn, Grw",
    onet: ["Written Expression", "Information Ordering"],
    examples: ["functions", "scripts", "SQL", "regex", "spreadsheets", "config files"],
    typicalAsk: "write the function",
    engages: "left frontal and parietal regions, weakly specific (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Write the function signature and the first test yourself, then hand over the body.",
    lexicon: [
      { term: "function", weight: 1.2 },
      { term: "code", weight: 1.1 },
      { term: "implement", weight: 1.4 },
      { term: "script", weight: 1.2 },
      { term: "sql", weight: 1.3 },
      { term: "query", weight: 0.8 },
      { term: "regex", weight: 1.4 },
      { term: "class", weight: 0.6 },
      { term: "component", weight: 1 },
      { term: "endpoint", weight: 1.1 },
      { term: "api", weight: 0.7 },
      { term: "python", weight: 1 },
      { term: "javascript", weight: 1 },
      { term: "typescript", weight: 1 },
      { term: "react", weight: 0.9 },
      { term: "bash", weight: 1 },
      { term: "shell", weight: 0.8 },
      { term: "config", weight: 0.9 },
      { term: "yaml", weight: 1 },
      { term: "json", weight: 0.8 },
      { term: "spreadsheet", weight: 0.9 },
      { term: "excel formula", weight: 1.3 },
      { term: "refactor", weight: 1.1 },
      { term: "boilerplate", weight: 1.2 },
      { term: "snippet", weight: 1.1 },
      { term: "css", weight: 1 },
      { term: "html", weight: 0.9 },
      { term: "dockerfile", weight: 1.2 },
      { term: "migration", weight: 0.9 },
      { term: "unit test", weight: 1 },
      { term: "tests for", weight: 1 }
    ]
  },
  {
    id: "verbal",
    label: "Verbal expression",
    short: "Conversation, negotiation, explaining aloud",
    chc: "Gc",
    onet: ["Oral Expression", "Oral Comprehension"],
    examples: ["what to say in a meeting", "a reply to a message", "a toast", "a negotiation"],
    typicalAsk: "what should I say",
    engages: "language plus mentalizing regions (group-average)",
    decayClass: "slow",
    stabilityPrior: STABILITY_BY_CLASS.slow,
    practice: "Say your version out loud once before you ask for a script.",
    lexicon: [
      { term: "what should i say", weight: 1.6 },
      { term: "how do i tell", weight: 1.4 },
      { term: "how to tell", weight: 1.2 },
      { term: "reply to", weight: 1 },
      { term: "respond to", weight: 1 },
      { term: "text back", weight: 1.1 },
      { term: "message to", weight: 0.9 },
      { term: "conversation", weight: 1 },
      { term: "negotiate", weight: 1.3 },
      { term: "negotiation", weight: 1.3 },
      { term: "interview", weight: 0.9 },
      { term: "talk to", weight: 0.8 },
      { term: "speech", weight: 1.1 },
      { term: "toast", weight: 1 },
      { term: "apologize", weight: 1 },
      { term: "apologise", weight: 1 },
      { term: "ask my", weight: 0.8 },
      { term: "politely", weight: 0.9 },
      { term: "small talk", weight: 1.2 },
      { term: "explain to my", weight: 0.9 }
    ]
  },
  {
    id: "attention",
    label: "Sustained attention",
    short: "Deep work blocks, not offloaded but fragmented",
    chc: "Gs",
    onet: ["Selective Attention"],
    examples: ["a 90-minute focus block", "reading without switching"],
    typicalAsk: "(not asked of AI; degraded by switching)",
    engages: "dorsal attention network (group-average)",
    decayClass: "none",
    stabilityPrior: STABILITY_BY_CLASS.none,
    practice: "One 45-minute block with notifications off. Log it as practice.",
    lexicon: []
  }
];
var DOMAIN_IDS = DOMAINS.map((d) => d.id);
var DOMAIN_BY_ID = Object.fromEntries(
  DOMAINS.map((d) => [d.id, d])
);

// src/core/classify.ts
var MAX_DOMAINS = 3;
var MIN_WEIGHT = 0.15;
var LEAD_CHARS = 90;
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function termPattern(term) {
  const isWord = /^[a-z][a-z0-9'-]*$/.test(term);
  return isWord ? new RegExp(`\\b${escapeRegExp(term)}\\b`, "g") : new RegExp(escapeRegExp(term), "g");
}
var PATTERNS = DOMAINS.flatMap(
  (d) => d.lexicon.map((l) => ({ id: d.id, term: l.term, weight: l.weight, re: termPattern(l.term) }))
);
var ASK_PATTERNS = [
  { type: "hint", re: /\b(hint|hints|don'?t (tell|give) me the answer|without (giving|telling) (me )?the answer|guide me|socratic|nudge me|point me in|just a hint|don'?t solve it)\b/i },
  { type: "review", re: /\b(check my|review my|critique|feedback on|is this (right|correct|ok|okay)|proofread|what do you think of (my|this)|does this look|grade my|rate my|my (draft|attempt|version|code|solution|essay|answer) (is|below|here)|here'?s my)\b/i },
  { type: "explain", re: /\b(explain|why (does|doesn'?t|do|don'?t|is|isn'?t|are|aren'?t|did|didn'?t|won'?t|can'?t|couldn'?t|would|wouldn'?t)|how (does|did|come)|how do (they|you|we|these|those|it)|walk me through|help me understand|what'?s the difference|what is the difference|teach me|intuition (for|behind))\b/i },
  { type: "answer", re: /\b(write|draft|generate|create|make|produce|give me|solve|calculate|compute|fix this|just do|complete|finish|full (code|essay|draft|solution)|the answer|implement|build me|rewrite|translate|convert|summarize|summarise|list)\b/i }
];
var GENERIC_VERBS = /* @__PURE__ */ new Set(["write", "rewrite"]);
var INTERACTIVE_RE = /\b(let'?s (discuss|argue|debate|work through)|push back|argue with me|challenge my|steelman|devil'?s advocate|back and forth|pair (on|with me))\b/i;
var CONSTRUCTIVE_RE = /\b(i (wrote|drafted|tried|attempted|made|built)|my (draft|attempt|version|solution|take)|here'?s (my|what i)|i think (the answer|it'?s)|my guess)\b/i;
function classifyPrompt(raw) {
  const text = raw.toLowerCase().replace(/\s+/g, " ").trim();
  const lead = text.slice(0, LEAD_CHARS);
  const scores = /* @__PURE__ */ new Map();
  const signals = /* @__PURE__ */ new Set();
  let genericComposition = 0;
  for (const p of PATTERNS) {
    const hits = text.match(p.re);
    if (!hits) continue;
    const count = Math.min(hits.length, 2);
    const leadBoost = p.re.test(lead) ? 1.5 : 1;
    p.re.lastIndex = 0;
    const contribution = p.weight * count * leadBoost;
    scores.set(p.id, (scores.get(p.id) ?? 0) + contribution);
    if (p.id === "composition" && GENERIC_VERBS.has(p.term)) genericComposition += contribution;
    signals.add(p.term);
  }
  if (/```|\bdef |\bfunction\b|=>|;\s*$|\bimport\b|\bconst\b|\breturn\b/.test(text)) {
    scores.set("implementation", (scores.get("implementation") ?? 0) + 1.5);
    signals.add("code-shaped text");
  }
  if ((scores.get("implementation") ?? 0) > 0 && genericComposition > 0) {
    scores.set("composition", Math.max(0, (scores.get("composition") ?? 0) - genericComposition));
  }
  if (/\d+\s*[+\-*/×÷^%]\s*\d+|\b\d+(\.\d+)?\s*(%|percent|kg|km|miles|usd|\$)/.test(text)) {
    scores.set("quantitative", (scores.get("quantitative") ?? 0) + 1);
    signals.add("numbers with operators or units");
  }
  if (text.length > 1200 && /\b(summar|tl;dr|key points|main points)/.test(text)) {
    scores.set("synthesis", (scores.get("synthesis") ?? 0) + 1.5);
    signals.add("long pasted text");
  }
  let domains = rankDomains(scores);
  let confidence;
  if (domains.length === 0) {
    const fallback = /\?\s*$/.test(text) ? "recall" : /^(write|draft|make|create)\b/.test(text) ? "composition" : "analysis";
    domains = [{ id: fallback, weight: 1 }];
    confidence = 0.2;
    signals.add("no lexicon hit; prompt shape");
  } else {
    const total = [...scores.values()].reduce((a, b) => a + b, 0);
    confidence = Math.min(1, domains[0].weight * Math.min(1, total / 3));
  }
  const askType = detectAskType(text);
  const icap = detectIcap(text, askType);
  return { domains, icap, askType, confidence: round2(confidence), signals: [...signals].slice(0, 8) };
}
function rankDomains(scores) {
  const entries = [...scores.entries()].filter(([, s]) => s > 0).sort((a, b) => b[1] - a[1]);
  if (entries.length === 0) return [];
  const total = entries.reduce((a, [, s]) => a + s, 0);
  let kept = entries.map(([id, s]) => ({ id, weight: s / total })).filter((d, i) => i === 0 || d.weight >= MIN_WEIGHT).slice(0, MAX_DOMAINS);
  const keptTotal = kept.reduce((a, d) => a + d.weight, 0);
  kept = kept.map((d) => ({ id: d.id, weight: round2(d.weight / keptTotal) }));
  return kept;
}
function detectAskType(text) {
  for (const p of ASK_PATTERNS) {
    if (p.re.test(text)) return p.type;
  }
  return "other";
}
function detectIcap(text, askType) {
  if (INTERACTIVE_RE.test(text)) return "interactive";
  if (CONSTRUCTIVE_RE.test(text) || askType === "hint") return "constructive";
  if (askType === "review" || askType === "explain") return "active";
  if (askType === "answer") return "passive";
  return "active";
}
function round2(n) {
  return Math.round(n * 100) / 100;
}

// src/core/policy.ts
var CONCEPTUAL = /* @__PURE__ */ new Set([
  "analysis",
  "composition",
  "quantitative",
  "planning",
  "ideation",
  "synthesis",
  "navigation",
  "verbal"
]);
var THRESHOLDS = {
  gentle: { self: 0.7, scaffold: 0.45, copilot: 0.2 },
  standard: { self: 0.55, scaffold: 0.35, copilot: 0.15 },
  firm: { self: 0.45, scaffold: 0.25, copilot: 0.1 }
};
function recommend(input) {
  const { classification, states, settings, capacity } = input;
  const byId = new Map(states.map((s) => [s.id, s]));
  const primary = classification.domains[0];
  const state = primary ? byId.get(primary.id) : void 0;
  const reasons = [];
  if (classification.askType === "hint") {
    reasons.push("You asked for a hint, so the model scaffolds instead of answering.");
    return build("scaffold", classification, reasons, capacity, primary?.id);
  }
  if (classification.askType === "review") {
    reasons.push("You did the work and asked for a review. The model critiques; it does not rewrite.");
    return build("copilot", classification, reasons, capacity, primary?.id, "Critique the person's version. Point at specific lines. Do not produce a replacement unless asked twice.");
  }
  let score = 0;
  if (state) {
    const staleness = 1 - state.retrievability;
    score += staleness;
    const label = DOMAIN_BY_ID[state.id].label;
    if (state.status === "fallow" && state.daysFallow === null) {
      reasons.push(`${label} has no self-done work in the ledger at all.`);
    } else if (state.status === "fallow" || state.status === "stale") {
      reasons.push(`${label} has lain fallow ${state.daysFallow} days (retrievability ${state.retrievability.toFixed(2)}).`);
    } else if (state.status === "fading") {
      reasons.push(`${label} is fading (retrievability ${state.retrievability.toFixed(2)}).`);
    } else {
      reasons.push(`${label} is fresh (retrievability ${state.retrievability.toFixed(2)}).`);
    }
    if (state.delegatedCount30d >= 5 && state.selfCount30d === 0) {
      score += 0.15;
      reasons.push(`Delegated ${state.delegatedCount30d} times in 30 days, done yourself 0 times.`);
    }
  }
  if (primary && settings.keepList.includes(primary.id)) {
    score += 0.35;
    reasons.push(`${DOMAIN_BY_ID[primary.id].label} is on your keep list.`);
  }
  if (primary && CONCEPTUAL.has(primary.id) && classification.askType !== "explain") {
    score += 0.15;
  } else if (primary && (primary.id === "implementation" || primary.id === "recall")) {
    score -= 0.1;
    reasons.push("Procedural work gains little from attempt-first, so the bar for pushing back is higher.");
  }
  if (capacity < 0.4) {
    score -= 0.3;
    reasons.push("Capacity is low right now. Delegating is the sane call; practice when rested.");
  } else if (capacity > 0.7) {
    score += 0.1;
  }
  if (input.deadline) {
    score -= 0.4;
    reasons.push("Deadline flag set.");
  }
  if (classification.icap === "constructive" || classification.icap === "interactive") {
    score -= 0.2;
    reasons.push("You brought your own attempt, which already counts as practice.");
  }
  const t = THRESHOLDS[settings.intensity];
  const mode = score >= t.self ? "self" : score >= t.scaffold ? "scaffold" : score >= t.copilot ? "copilot" : "delegate";
  if (classification.askType === "explain" && mode === "self") {
    reasons.push("Explanations are learning. Scaffolded rather than refused.");
    return build("scaffold", classification, reasons, capacity, primary?.id);
  }
  return build(mode, classification, reasons, capacity, primary?.id);
}
function build(mode, c, reasons, capacity, domainId, scaffoldOverride) {
  const practice = domainId ? DOMAIN_BY_ID[domainId].practice : "";
  const scaffold = scaffoldOverride ?? SCAFFOLDS[mode](practice);
  return { mode, domains: c.domains, reasons, scaffold, capacity };
}
var SCAFFOLDS = {
  self: (practice) => `Do this one yourself. Set a 15-minute timer. If you are still stuck at the end, come back and ask for a hint, not the answer. ${practice}`.trim(),
  scaffold: () => "Give hints, questions and structure. Withhold the finished answer. Ask the person to attempt each step before revealing the next. Do not write the final artifact.",
  copilot: () => "Draft it, then require one of these before the person accepts it: explain it back in their own words, change three specific things, or answer a three-item checklist about it.",
  delegate: () => "Do the task. It is logged as delegated. If ideas are involved, mark which ones came from the model."
};
var MODE_LABEL = {
  self: "Do it yourself",
  scaffold: "Scaffold",
  copilot: "Co-pilot",
  delegate: "Delegate"
};

// src/core/scheduler.ts
var DECAY_W = 0.5;
var FACTOR = Math.pow(0.9, -1 / DECAY_W) - 1;
var MAX_STABILITY_DAYS = 365;
var ICAP_GAIN = {
  interactive: 2,
  constructive: 1.6,
  active: 1,
  passive: 0.25
};
var STATUS_THRESHOLDS = [
  ["fresh", 0.85],
  ["fading", 0.7],
  ["stale", 0.55]
];
var DAY_MS = 864e5;
function retrievability(daysSince, stability) {
  if (!Number.isFinite(stability)) return 1;
  if (daysSince <= 0) return 1;
  return Math.pow(1 + FACTOR * daysSince / stability, -DECAY_W);
}
function nextStability(stability, review) {
  if (!Number.isFinite(stability)) return stability;
  const effort = review.minutes === void 0 ? 1 : Math.min(1.5, 0.5 + review.minutes / 60);
  const difficultyBonus = Math.max(0.2, 1.2 - review.r);
  const share = review.shared ? 0.7 : 1;
  const growth = 1 + ICAP_GAIN[review.icap] * difficultyBonus * effort * share * review.weight;
  return Math.min(MAX_STABILITY_DAYS, stability * growth);
}
function statusFor(r, everPracticed) {
  if (!everPracticed) return "fallow";
  for (const [status, threshold] of STATUS_THRESHOLDS) if (r >= threshold) return status;
  return "fallow";
}
function daysBetween(fromIso, toMs) {
  return (toMs - Date.parse(fromIso)) / DAY_MS;
}
function deriveDomainStates(events, now = /* @__PURE__ */ new Date()) {
  const nowMs = now.getTime();
  const sorted = [...events].sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts));
  const ledgerStart = sorted.length ? sorted[0].ts : now.toISOString();
  const cutoff30 = nowMs - 30 * DAY_MS;
  const acc = /* @__PURE__ */ new Map();
  for (const id of DOMAIN_IDS) acc.set(id, { stability: DOMAIN_BY_ID[id].stabilityPrior, self30: 0, del30: 0 });
  for (const e of sorted) {
    const tsMs = Date.parse(e.ts);
    for (const dw of e.domains) {
      const a = acc.get(dw.id);
      if (!a) continue;
      const isPractice = e.actor === "self" || e.actor === "shared";
      if (isPractice) {
        const since = a.lastSelfAt ? (tsMs - Date.parse(a.lastSelfAt)) / DAY_MS : daysBetween(ledgerStart, tsMs);
        const r = retrievability(Math.max(0, since), a.stability);
        a.stability = nextStability(a.stability, {
          icap: e.icap,
          r,
          weight: dw.weight,
          minutes: e.minutes,
          shared: e.actor === "shared"
        });
        a.lastSelfAt = e.ts;
        if (tsMs >= cutoff30) a.self30 += 1;
      } else {
        a.lastDelegatedAt = e.ts;
        if (tsMs >= cutoff30) a.del30 += 1;
      }
    }
  }
  return DOMAIN_IDS.map((id) => {
    const a = acc.get(id);
    const ever = a.lastSelfAt !== void 0;
    const since = ever ? daysBetween(a.lastSelfAt, nowMs) : daysBetween(ledgerStart, nowMs);
    const r = retrievability(Math.max(0, since), a.stability);
    return {
      id,
      stability: round1(a.stability),
      lastSelfAt: a.lastSelfAt,
      lastDelegatedAt: a.lastDelegatedAt,
      selfCount30d: a.self30,
      delegatedCount30d: a.del30,
      retrievability: round3(r),
      daysFallow: ever ? Math.floor(since) : null,
      status: statusFor(r, ever)
    };
  });
}
function round1(n) {
  return Number.isFinite(n) ? Math.round(n * 10) / 10 : n;
}
function round3(n) {
  return Math.round(n * 1e3) / 1e3;
}

// src/core/time.ts
function localDateKey(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// src/core/summary.ts
var DAY_MS2 = 864e5;
function todaySleep(settings, now) {
  const key = localDateKey(now);
  return settings.sleepLog[key] ?? settings.sleep;
}
function buildSnapshot(events, settings, now = /* @__PURE__ */ new Date(), signals = []) {
  const states = deriveDomainStates(events, now);
  const sleep = todaySleep(settings, now);
  const capacity = capacityAt(now, sleep, settings.chronotype, events);
  const curve = dayCurve(sleep, settings.chronotype, 30);
  const sorted = [...events].sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts));
  const from = sorted[0]?.ts;
  const to = sorted.at(-1)?.ts;
  const bySource = {};
  let delegated = 0;
  let shared = 0;
  let self = 0;
  for (const e of events) {
    bySource[e.source] = (bySource[e.source] ?? 0) + 1;
    if (e.actor === "ai") delegated += 1;
    else if (e.actor === "shared") shared += 1;
    else self += 1;
  }
  const days = from && to ? Math.max(1, Math.round((Date.parse(to) - Date.parse(from)) / DAY_MS2) + 1) : 0;
  return {
    generatedAt: now.toISOString(),
    states,
    capacity,
    curve,
    nudges: buildNudges(states, settings),
    totals: {
      events: events.length,
      delegated,
      shared,
      self,
      delegatedShare: events.length ? Math.round(delegated / events.length * 100) / 100 : 0,
      bySource,
      days,
      from,
      to
    },
    weekly: weeklySeries(events, now),
    drift: driftByDomain(events, now),
    attention: attentionSummary(signals, settings, now),
    pause: pauseSummary(signals, now),
    recent: sorted.slice(-25).reverse()
  };
}
function driftByDomain(events, now) {
  const nowMs = now.getTime();
  const counts = /* @__PURE__ */ new Map();
  for (const id of Object.keys(DOMAIN_BY_ID)) counts.set(id, [0, 1, 2, 3].map(() => ({ self: 0, delegated: 0 })));
  for (const e of events) {
    const age = nowMs - Date.parse(e.ts);
    if (age < 0 || age >= 28 * DAY_MS2) continue;
    const window = 3 - Math.floor(age / (7 * DAY_MS2));
    for (const dw of e.domains) {
      const row = counts.get(dw.id)?.[window];
      if (!row) continue;
      if (e.actor === "ai") row.delegated += 1;
      else row.self += 1;
    }
  }
  const out = {};
  for (const [id, windows] of counts) {
    const shares = windows.map((w) => {
      const total = w.self + w.delegated;
      return total >= 3 ? w.delegated / total : null;
    });
    if (shares.some((v) => v === null)) {
      out[id] = "unknown";
      continue;
    }
    const s = shares;
    const up = s[1] > s[0] && s[2] > s[1] && s[3] > s[2];
    const down = s[1] < s[0] && s[2] < s[1] && s[3] < s[2];
    out[id] = up ? "rising" : down ? "falling" : "flat";
  }
  return out;
}
function attentionSummary(signals, settings, now) {
  const today = localDateKey(now);
  const cutoff = localDateKey(new Date(now.getTime() - 6 * DAY_MS2));
  const days = signals.filter((s) => s.kind === "attention-day" && s.day >= cutoff && s.day <= today).sort((a, b) => a.day.localeCompare(b.day));
  return { today: days.find((d) => d.day === today), week: days, budgetMin: settings.entertainmentBudgetMin };
}
function pauseSummary(signals, now) {
  const nowMs = now.getTime();
  const weekMs = nowMs - 7 * DAY_MS2;
  const pauses = signals.filter((s) => s.kind === "pause" && Date.parse(s.ts) <= nowMs);
  const week = pauses.filter((p) => Date.parse(p.ts) >= weekMs);
  const todays = week.filter((p) => localDateKey(new Date(p.ts)) === localDateKey(now));
  const sites = /* @__PURE__ */ new Map();
  for (const p of todays) sites.set(p.site, (sites.get(p.site) ?? 0) + 1);
  const weekClosed = week.filter((p) => p.outcome === "closed").length;
  return {
    todayOpens: todays.length,
    todayClosed: todays.filter((p) => p.outcome === "closed").length,
    weekOpens: week.length,
    weekClosed,
    closeRate7d: week.length ? Math.round(weekClosed / week.length * 100) / 100 : null,
    sitesToday: [...sites.entries()].map(([site, opens]) => ({ site, opens })).sort((a, b) => b.opens - a.opens)
  };
}
function buildNudges(states, settings, limit = 3) {
  const keep = new Set(settings.keepList);
  const candidates = states.filter((s) => s.id !== "attention").filter((s) => s.status === "stale" || s.status === "fallow" || s.status === "fading" && keep.has(s.id)).sort((a, b) => {
    const ka = keep.has(a.id) ? 1 : 0;
    const kb = keep.has(b.id) ? 1 : 0;
    if (ka !== kb) return kb - ka;
    if (a.delegatedCount30d !== b.delegatedCount30d) return b.delegatedCount30d - a.delegatedCount30d;
    return a.retrievability - b.retrievability;
  }).slice(0, limit);
  return candidates.map((s) => {
    const spec = DOMAIN_BY_ID[s.id];
    const fallow = s.daysFallow === null ? "no self-done work on record" : `${s.daysFallow} days since you last did this yourself`;
    const delegated = s.delegatedCount30d > 0 ? `, delegated ${s.delegatedCount30d} times in the last 30 days` : "";
    return {
      domain: s.id,
      headline: `${spec.label}: ${fallow}${delegated}.`,
      detail: `Retrievability ${s.retrievability.toFixed(2)}. Typical ask: "${spec.typicalAsk}".`,
      practice: spec.practice
    };
  });
}
function weekStart(ms) {
  const d = new Date(ms);
  const day = d.getUTCDay();
  const diff = (day + 6) % 7;
  const monday = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate() - diff));
  return monday.toISOString().slice(0, 10);
}
function weeklySeries(events, now, weeks = 12) {
  const nowMs = now.getTime();
  const startMs = Date.parse(weekStart(nowMs)) - (weeks - 1) * 7 * DAY_MS2;
  const keys = [];
  for (let i = 0; i < weeks; i++) keys.push(new Date(startMs + i * 7 * DAY_MS2).toISOString().slice(0, 10));
  const out = {};
  for (const id of Object.keys(DOMAIN_BY_ID)) {
    out[id] = keys.map((day) => ({ day, self: 0, delegated: 0 }));
  }
  const index = new Map(keys.map((k, i) => [k, i]));
  for (const e of events) {
    const ms = Date.parse(e.ts);
    if (ms < startMs || ms > nowMs) continue;
    const i = index.get(weekStart(ms));
    if (i === void 0) continue;
    for (const dw of e.domains) {
      const row = out[dw.id]?.[i];
      if (!row) continue;
      if (e.actor === "ai") row.delegated += 1;
      else row.self += 1;
    }
  }
  return out;
}

// src/core/assess.ts
function assess(text, ledger, opts = {}) {
  const now = opts.now ?? /* @__PURE__ */ new Date();
  const classification = classifyPrompt(text);
  const states = deriveDomainStates(ledger.events, now);
  const capacity = capacityAt(now, todaySleep(ledger.settings, now), ledger.settings.chronotype, ledger.events);
  const recommendation = recommend({
    classification,
    states,
    settings: ledger.settings,
    capacity: capacity.value,
    deadline: opts.deadline
  });
  return { classification, recommendation, context: contextFor(classification, recommendation) };
}
function contextFor(c, r) {
  const domains = c.domains.map((d) => `${DOMAIN_BY_ID[d.id].label} (${Math.round(d.weight * 100)}%)`).join(", ");
  const lines = [
    `[Fallow] Engagement mode for this request: ${MODE_LABEL[r.mode].toUpperCase()}.`,
    `Domains: ${domains}. Ask type: ${c.askType}. Engagement level requested: ${c.icap}.`,
    `Why: ${r.reasons.join(" ")}`,
    `How to respond: ${r.scaffold}`
  ];
  if (r.mode === "self") {
    lines.push("Do not produce the finished artifact. Offer the timer and one first step. If the person insists, ask them to log it as delegated first.");
  }
  return lines.join("\n");
}

// src/core/events.ts
function fnv1a(input) {
  let h = 2166136261;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}
function actorFor(c) {
  if (c.icap === "interactive" || c.icap === "constructive") return "shared";
  if (c.askType === "review" || c.askType === "explain") return "shared";
  return "ai";
}
var EXCERPT_CHARS = 140;
function excerptOf(text) {
  const t = text.replace(/\s+/g, " ").trim();
  return t.length > EXCERPT_CHARS ? `${t.slice(0, EXCERPT_CHARS - 1)}\u2026` : t;
}
function eventFromPrompt(text, opts) {
  const c = classifyPrompt(text);
  const key = opts.key ?? `${opts.source}|${opts.ts}|${text}`;
  return {
    id: fnv1a(key),
    ts: opts.ts,
    source: opts.source,
    excerpt: opts.keepExcerpt === false ? void 0 : excerptOf(text),
    domains: c.domains,
    icap: c.icap,
    askType: c.askType,
    actor: actorFor(c),
    conversationId: opts.conversationId
  };
}

// src/core/ledger.ts
var DEFAULT_SETTINGS = {
  keepList: ["composition", "analysis", "quantitative"],
  intensity: "standard",
  chronotype: "intermediate",
  sleep: { bed: "23:30", wake: "07:30" },
  sleepLog: {},
  entertainmentSites: ["youtube.com", "tiktok.com", "instagram.com", "x.com", "twitter.com", "reddit.com", "facebook.com", "netflix.com", "twitch.tv"],
  entertainmentBudgetMin: 60,
  pauseSeconds: 10,
  syncText: false
};
function emptyLedger() {
  return {
    version: 1,
    events: [],
    signals: [],
    settings: { ...DEFAULT_SETTINGS, keepList: [...DEFAULT_SETTINGS.keepList], entertainmentSites: [...DEFAULT_SETTINGS.entertainmentSites], sleepLog: {} }
  };
}
function normalizeLedger(parsed) {
  return {
    version: 1,
    events: Array.isArray(parsed?.events) ? parsed.events : [],
    signals: Array.isArray(parsed?.signals) ? parsed.signals : [],
    settings: { ...DEFAULT_SETTINGS, ...parsed?.settings ?? {}, sleepLog: parsed?.settings?.sleepLog ?? {} }
  };
}
var ACTORS = ["self", "ai", "shared"];
var ICAPS = ["passive", "active", "constructive", "interactive"];
var SOURCES = ["import-chatgpt", "import-claude", "hook-claude-code", "hook-cursor", "extension-chat", "activitywatch", "practice", "gate", "manual", "seed"];
function isActor(v) {
  return typeof v === "string" && ACTORS.includes(v);
}
function isIcap(v) {
  return typeof v === "string" && ICAPS.includes(v);
}
function isSource(v) {
  return typeof v === "string" && SOURCES.includes(v);
}
function isDomainWeight(d) {
  return !!d && typeof d === "object" && DOMAIN_IDS.includes(d.id) && typeof d.weight === "number";
}
function buildPromptEvent(input, now = /* @__PURE__ */ new Date()) {
  const text = typeof input.text === "string" ? input.text.trim() : "";
  if (!text) return null;
  const ts = typeof input.ts === "string" && !Number.isNaN(Date.parse(input.ts)) ? new Date(input.ts).toISOString() : now.toISOString();
  const source = isSource(input.source) ? input.source : "manual";
  const event = eventFromPrompt(text, { source, ts, keepExcerpt: input.keepExcerpt !== false });
  if (isActor(input.actor)) event.actor = input.actor;
  if (isIcap(input.icap)) event.icap = input.icap;
  if (typeof input.minutes === "number" && input.minutes > 0) event.minutes = Math.round(input.minutes);
  if (typeof input.demanding === "boolean") event.demanding = input.demanding;
  if (input.ideaOrigin === "self" || input.ideaOrigin === "ai") event.ideaOrigin = input.ideaOrigin;
  if (Array.isArray(input.domains)) {
    const domains = input.domains.filter(isDomainWeight);
    if (domains.length) event.domains = domains;
  }
  return event;
}
function parseSignal(raw, now) {
  if (!raw || typeof raw !== "object") return null;
  const r = raw;
  const ts = typeof r.ts === "string" && !Number.isNaN(Date.parse(r.ts)) ? new Date(r.ts).toISOString() : now;
  if (r.kind === "pause") {
    const site = typeof r.site === "string" ? r.site.toLowerCase().replace(/^www\./, "").slice(0, 120) : "";
    const outcome = r.outcome === "closed" ? "closed" : r.outcome === "continued" ? "continued" : null;
    if (!site || !outcome) return null;
    const waitedSeconds = typeof r.waitedSeconds === "number" ? Math.max(0, Math.round(r.waitedSeconds)) : 0;
    const s = { id: fnv1a(`pause|${ts}|${site}|${outcome}`), ts, kind: "pause", site, outcome, waitedSeconds };
    return s;
  }
  if (r.kind === "attention-day") {
    const day = typeof r.day === "string" && /^\d{4}-\d{2}-\d{2}$/.test(r.day) ? r.day : null;
    if (!day) return null;
    const num = (v) => typeof v === "number" && Number.isFinite(v) ? Math.max(0, Math.round(v * 10) / 10) : 0;
    const top = Array.isArray(r.top) ? r.top.filter((t) => !!t && typeof t === "object" && typeof t.name === "string" && typeof t.minutes === "number").slice(0, 8).map((t) => ({ name: t.name.slice(0, 80), minutes: Math.round(t.minutes) })) : [];
    const s = {
      id: fnv1a(`attention|${day}`),
      ts: typeof r.ts === "string" ? ts : `${day}T12:00:00.000Z`,
      kind: "attention-day",
      day,
      activeMin: num(r.activeMin),
      switchesPerHour: num(r.switchesPerHour),
      longestBlockMin: num(r.longestBlockMin),
      entertainmentMin: num(r.entertainmentMin),
      top
    };
    return s;
  }
  return null;
}
function addEventsTo(ledger, events) {
  const seen = new Set(ledger.events.map((e) => e.id));
  let added = 0;
  for (const e of events) {
    if (seen.has(e.id)) continue;
    seen.add(e.id);
    ledger.events.push(e);
    added += 1;
  }
  ledger.events.sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts));
  return { added, total: ledger.events.length };
}
function addSignalsTo(ledger, signals) {
  const seen = new Set(ledger.signals.map((s) => s.id));
  let added = 0;
  for (const s of signals) {
    if (s.kind === "attention-day") {
      const idx = ledger.signals.findIndex((x) => x.kind === "attention-day" && x.day === s.day);
      if (idx >= 0) {
        ledger.signals[idx] = s;
        added += 1;
        continue;
      }
    }
    if (seen.has(s.id)) continue;
    seen.add(s.id);
    ledger.signals.push(s);
    added += 1;
  }
  ledger.signals.sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts));
  return { added, total: ledger.signals.length };
}
function validSleep(s) {
  if (!s || typeof s !== "object") return false;
  try {
    parseClock(s.bed);
    parseClock(s.wake);
    return true;
  } catch {
    return false;
  }
}
function applySettingsPatch(ledger, body) {
  const patch = {};
  if (Array.isArray(body.keepList)) patch.keepList = body.keepList.filter((d) => DOMAIN_IDS.includes(d));
  if (typeof body.intensity === "string" && ["gentle", "standard", "firm"].includes(body.intensity)) patch.intensity = body.intensity;
  if (typeof body.chronotype === "string" && ["morning", "intermediate", "evening"].includes(body.chronotype)) patch.chronotype = body.chronotype;
  if (validSleep(body.sleep)) patch.sleep = body.sleep;
  if (typeof body.sleepDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.sleepDate) && validSleep(body.sleepForDate)) {
    patch.sleepLog = { ...ledger.settings.sleepLog, [body.sleepDate]: body.sleepForDate };
  }
  if (Array.isArray(body.entertainmentSites)) {
    patch.entertainmentSites = body.entertainmentSites.filter((h) => typeof h === "string").map((h) => h.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/.*$/, "")).filter((h) => /^[a-z0-9.-]+$/.test(h));
  }
  if (typeof body.entertainmentBudgetMin === "number" && body.entertainmentBudgetMin >= 0) patch.entertainmentBudgetMin = Math.round(body.entertainmentBudgetMin);
  if (typeof body.pauseSeconds === "number" && body.pauseSeconds >= 0 && body.pauseSeconds <= 120) patch.pauseSeconds = Math.round(body.pauseSeconds);
  if (typeof body.syncText === "boolean") patch.syncText = body.syncText;
  ledger.settings = { ...ledger.settings, ...patch };
  return ledger.settings;
}
export {
  addEventsTo,
  addSignalsTo,
  applySettingsPatch,
  assess,
  buildPromptEvent,
  buildSnapshot,
  emptyLedger,
  localDateKey,
  normalizeLedger,
  parseSignal
};
