"""Garden plot tiles: one 16x16 tile per domain status, drawn as code."""
from __future__ import annotations

import json
from pathlib import Path

from PIL import Image

T = 16
OUT = Path(__file__).parent / "out"
TS_OUT = Path(__file__).resolve().parents[2] / "src" / "pixel"

PALETTE = {
    ".": None,
    "s": "#a0784e",  # soil
    "S": "#7a5a3a",  # soil dark / edge
    "t": "#b48a5c",  # soil light
    "x": "#c8b08a",  # dry soil
    "X": "#9c8763",  # dry soil edge
    "c": "#6e5a40",  # crack
    "g": "#6e8a4a",  # leaf
    "G": "#4f6b3a",  # leaf dark
    "h": "#9fbf6a",  # leaf light
    "y": "#b9a64a",  # yellowing leaf
    "Y": "#8c7d35",  # yellowing dark
    "r": "#8a6a3c",  # dry stubble
    "p": "#e86f68",  # flower
    "w": "#fff3ec",  # flower centre
}


def blank():
    return [["." for _ in range(T)] for _ in range(T)]


def soil(g, dry=False):
    fill, edge, light = ("x", "X", "x") if dry else ("s", "S", "t")
    for y in range(4, 16):
        for x in range(1, 15):
            g[y][x] = fill
    for x in range(1, 15):
        g[4][x] = light if not dry else fill
        g[15][x] = edge
    for y in range(4, 16):
        g[y][1] = edge if y > 4 else g[y][1]
        g[y][14] = edge
    # texture dots
    for x, y in [(4, 8), (9, 7), (12, 11), (6, 13), (3, 11), (11, 14)]:
        g[y][x] = edge


def stamp(g, pts, key):
    for x, y in pts:
        if 0 <= x < T and 0 <= y < T:
            g[y][x] = key


def tile(status: str):
    g = blank()
    if status == "fallow":
        soil(g, dry=True)
        stamp(g, [(3, 6), (4, 7), (5, 7), (6, 8), (6, 9), (7, 10)], "c")
        stamp(g, [(10, 5), (10, 6), (11, 7), (12, 8), (12, 9)], "c")
        stamp(g, [(8, 12), (9, 13), (10, 13), (11, 14)], "c")
        return ["".join(r) for r in g]
    soil(g, dry=(status == "stale"))
    if status == "fresh":
        # a full plant with a flower
        stamp(g, [(8, 4), (8, 3), (8, 2), (8, 1)], "G")
        stamp(g, [(4, 3), (5, 2), (6, 2), (5, 3), (6, 3), (7, 3), (5, 4), (6, 4), (7, 4)], "g")
        stamp(g, [(9, 3), (10, 2), (11, 2), (12, 3), (10, 3), (11, 3), (9, 4), (10, 4), (11, 4)], "g")
        stamp(g, [(5, 2), (6, 3), (10, 2), (11, 3)], "h")
        stamp(g, [(7, 0), (9, 0), (8, 1), (7, 1), (9, 1)], "p")
        stamp(g, [(8, 0)], "w")
        stamp(g, [(2, 5), (3, 4), (3, 5), (13, 4), (13, 5), (14, 5)], "g")
        stamp(g, [(3, 4), (13, 4)], "h")
    elif status == "fading":
        stamp(g, [(8, 4), (8, 3), (8, 2)], "Y")
        stamp(g, [(6, 4), (7, 3), (7, 4)], "y")
        stamp(g, [(9, 3), (10, 4), (9, 4)], "y")
        stamp(g, [(7, 3)], "g")
        stamp(g, [(4, 5), (12, 5)], "y")
    elif status == "stale":
        stamp(g, [(7, 4), (7, 3), (9, 4), (9, 3), (12, 4)], "r")
        stamp(g, [(4, 4), (4, 3)], "r")
    return ["".join(r) for r in g]


TILES = {s: tile(s) for s in ("fresh", "fading", "stale", "fallow")}


def to_image(rows, scale=1):
    img = Image.new("RGBA", (T, T), (0, 0, 0, 0))
    px = img.load()
    for y, row in enumerate(rows):
        for x, k in enumerate(row):
            h = PALETTE[k]
            if h:
                px[x, y] = tuple(int(h[i : i + 2], 16) for i in (1, 3, 5)) + (255,)
    return img.resize((T * scale, T * scale), Image.NEAREST) if scale != 1 else img


def write_ts():
    TS_OUT.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by scripts/pixel/tiles.py. Edit the Python, not this file.",
        "export const TILE_PALETTE: Record<string, string | null> = " + json.dumps(PALETTE, indent=2) + ";",
        "export const TILES: Record<string, string[]> = " + json.dumps(TILES, indent=2) + ";",
        "export const TILE_SIZE = 16;",
        "",
    ]
    (TS_OUT / "tiles.ts").write_text("\n".join(lines))


if __name__ == "__main__":
    write_ts()
    scale = 10
    row = Image.new("RGBA", (T * scale * 4 + 30, T * scale), (243, 232, 210, 255))
    for i, s in enumerate(TILES):
        row.paste(to_image(TILES[s], scale), (i * (T * scale + 10), 0), to_image(TILES[s], scale))
    row.save(OUT / "tiles-row.png")
    print("wrote", OUT / "tiles-row.png", "and", TS_OUT / "tiles.ts")
