import type { DecayClass, DomainId } from "./types";

/**
 * The Fallow domain set.
 *
 * Eleven cognitive domains chosen for where AI offloading lands, anchored to
 * Cattell-Horn-Carroll broad abilities and O*NET cognitive abilities.
 *
 * `engages` is deliberately hedged: it describes group-average fMRI engagement,
 * not what exercising the domain does to the brain (reverse inference is weak,
 * Poldrack 2006). `stabilityPrior` is the number of days at which retrievability
 * falls to 0.9 with no practice; the classes follow Arthur et al. 1998, where
 * abstract, feedback-free cognitive procedures decay fastest. These are priors
 * to be fitted from real practice data, not measurements.
 */
export interface DomainSpec {
  id: DomainId;
  label: string;
  short: string;
  chc: string;
  onet: string[];
  examples: string[];
  typicalAsk: string;
  engages: string;
  decayClass: DecayClass;
  stabilityPrior: number;
  /** A concrete self-practice suggestion, phrased as a task the person already has. */
  practice: string;
  /** Lexicon: lowercase tokens or phrases. Phrases may contain spaces. */
  lexicon: Array<{ term: string; weight: number }>;
}

const STABILITY_BY_CLASS: Record<DecayClass, number> = {
  fast: 14,
  medium: 30,
  slow: 60,
  none: Number.POSITIVE_INFINITY,
};

export const DOMAINS: DomainSpec[] = [
  {
    id: "composition",
    label: "Composition",
    short: "Drafting prose and argument",
    chc: "Grw, Gc",
    onet: ["Written Expression", "Originality"],
    examples: ["emails", "essays", "docs", "cover letters", "posts"],
    typicalAsk: "write me",
    engages: "left inferior frontal and temporal language network (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Write the first full draft of your next email or doc yourself, then ask for a critique.",
    lexicon: [
      { term: "write", weight: 1 },
      { term: "draft", weight: 1.2 },
      { term: "rewrite", weight: 0.8 },
      { term: "compose", weight: 1.2 },
      { term: "essay", weight: 1.3 },
      { term: "email", weight: 1 },
      { term: "cover letter", weight: 1.5 },
      { term: "paragraph", weight: 1 },
      { term: "blog", weight: 1 },
      { term: "post", weight: 0.5 },
      { term: "caption", weight: 0.8 },
      { term: "bio", weight: 0.8 },
      { term: "statement", weight: 0.8 },
      { term: "proofread", weight: 0.6 },
      { term: "tone", weight: 0.6 },
      { term: "wording", weight: 0.8 },
      { term: "phrase", weight: 0.6 },
      { term: "letter", weight: 0.7 },
      { term: "memo", weight: 1 },
      { term: "abstract", weight: 0.7 },
      { term: "intro", weight: 0.5 },
      { term: "conclusion", weight: 0.5 },
    ],
  },
  {
    id: "analysis",
    label: "Analytical reasoning",
    short: "Debugging, diagnosing, proving",
    chc: "Gf",
    onet: ["Deductive Reasoning", "Inductive Reasoning", "Problem Sensitivity"],
    examples: ["debugging", "diagnosing failures", "proofs", "root-cause work"],
    typicalAsk: "why doesn't this work",
    engages: "multiple-demand network, lateral prefrontal and parietal (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Before pasting the error, write down two hypotheses and test the cheaper one.",
    lexicon: [
      { term: "why", weight: 0.8 },
      { term: "why doesn't", weight: 1.5 },
      { term: "why does", weight: 1.2 },
      { term: "why isn't", weight: 1.5 },
      { term: "why won't", weight: 1.5 },
      { term: "why did", weight: 1.2 },
      { term: "debug", weight: 1.5 },
      { term: "bug", weight: 1.2 },
      { term: "error", weight: 1 },
      { term: "fails", weight: 0.8 },
      { term: "failing", weight: 0.8 },
      { term: "broken", weight: 0.8 },
      { term: "doesn't work", weight: 1.2 },
      { term: "does not work", weight: 1.2 },
      { term: "not working", weight: 1.2 },
      { term: "fix", weight: 0.9 },
      { term: "diagnose", weight: 1.3 },
      { term: "root cause", weight: 1.4 },
      { term: "prove", weight: 1.2 },
      { term: "proof", weight: 1.2 },
      { term: "logic", weight: 0.8 },
      { term: "reason", weight: 0.6 },
      { term: "stack trace", weight: 1.4 },
      { term: "traceback", weight: 1.4 },
      { term: "exception", weight: 1 },
      { term: "undefined", weight: 0.7 },
      { term: "null", weight: 0.5 },
      { term: "wrong", weight: 0.6 },
      { term: "compare", weight: 0.5 },
      { term: "evaluate", weight: 0.6 },
      { term: "tradeoff", weight: 0.8 },
      { term: "trade-off", weight: 0.8 },
    ],
  },
  {
    id: "quantitative",
    label: "Quantitative reasoning",
    short: "Math, estimation, statistics",
    chc: "Gq, Gf",
    onet: ["Mathematical Reasoning", "Number Facility"],
    examples: ["mental math", "unit conversions", "statistics", "back-of-envelope estimates"],
    typicalAsk: "calculate",
    engages: "bilateral intraparietal sulcus (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Estimate the answer to one significant figure before you compute it.",
    lexicon: [
      { term: "calculate", weight: 1.5 },
      { term: "compute", weight: 1 },
      { term: "math", weight: 1.3 },
      { term: "equation", weight: 1.2 },
      { term: "formula", weight: 1 },
      { term: "percent", weight: 0.9 },
      { term: "%", weight: 0.6 },
      { term: "average", weight: 0.8 },
      { term: "mean", weight: 0.5 },
      { term: "median", weight: 0.9 },
      { term: "probability", weight: 1.2 },
      { term: "statistic", weight: 1.2 },
      { term: "regression", weight: 1 },
      { term: "derivative", weight: 1.3 },
      { term: "integral", weight: 1.3 },
      { term: "solve for", weight: 1.3 },
      { term: "convert", weight: 0.7 },
      { term: "estimate", weight: 0.9 },
      { term: "how many", weight: 0.8 },
      { term: "how much", weight: 0.7 },
      { term: "budget", weight: 0.6 },
      { term: "interest rate", weight: 1 },
      { term: "p-value", weight: 1.3 },
      { term: "standard deviation", weight: 1.3 },
      { term: "sum", weight: 0.6 },
      { term: "total", weight: 0.4 },
    ],
  },
  {
    id: "recall",
    label: "Recall",
    short: "Names, facts, APIs, vocabulary",
    chc: "Gl, Gr",
    onet: ["Memorization"],
    examples: ["a function signature", "a date", "a word in another language", "who said what"],
    typicalAsk: "what is the",
    engages: "hippocampus and medial temporal lobe (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Guess first. Say the answer out loud, then check it.",
    lexicon: [
      { term: "what is the", weight: 0.9 },
      { term: "what's the", weight: 0.9 },
      { term: "what was", weight: 0.7 },
      { term: "who is", weight: 0.8 },
      { term: "who was", weight: 0.8 },
      { term: "when did", weight: 0.9 },
      { term: "when was", weight: 0.9 },
      { term: "remind me", weight: 1.3 },
      { term: "name of", weight: 1.1 },
      { term: "called", weight: 0.5 },
      { term: "definition", weight: 1 },
      { term: "define", weight: 1 },
      { term: "meaning of", weight: 1 },
      { term: "syntax for", weight: 1.2 },
      { term: "syntax", weight: 0.7 },
      { term: "capital of", weight: 1.2 },
      { term: "date of", weight: 0.9 },
      { term: "translate", weight: 0.9 },
      { term: "in spanish", weight: 0.8 },
      { term: "in french", weight: 0.8 },
      { term: "acronym", weight: 1 },
      { term: "stand for", weight: 1 },
      { term: "which command", weight: 1 },
      { term: "flag for", weight: 0.9 },
      { term: "shortcut", weight: 0.9 },
    ],
  },
  {
    id: "synthesis",
    label: "Reading and synthesis",
    short: "Reading closely, summarizing, connecting",
    chc: "Grw, Gc",
    onet: ["Written Comprehension", "Information Ordering"],
    examples: ["papers", "long threads", "contracts", "meeting notes"],
    typicalAsk: "summarize this",
    engages: "language network with default-mode regions (group-average)",
    decayClass: "medium",
    stabilityPrior: STABILITY_BY_CLASS.medium,
    practice: "Read the abstract and the figures, write a three-sentence summary, then compare.",
    lexicon: [
      { term: "summarize", weight: 1.6 },
      { term: "summary", weight: 1.4 },
      { term: "summarise", weight: 1.6 },
      { term: "tl;dr", weight: 1.6 },
      { term: "tldr", weight: 1.6 },
      { term: "key points", weight: 1.3 },
      { term: "main points", weight: 1.3 },
      { term: "takeaways", weight: 1.3 },
      { term: "this paper", weight: 1 },
      { term: "this article", weight: 1 },
      { term: "this document", weight: 0.9 },
      { term: "this thread", weight: 0.9 },
      { term: "read this", weight: 1 },
      { term: "what does this say", weight: 1.2 },
      { term: "in simple terms", weight: 0.8 },
      { term: "eli5", weight: 1 },
      { term: "overview", weight: 0.8 },
      { term: "digest", weight: 0.9 },
      { term: "notes on", weight: 0.8 },
      { term: "literature", weight: 0.8 },
      { term: "sources", weight: 0.5 },
      { term: "explain this", weight: 0.9 },
    ],
  },
  {
    id: "navigation",
    label: "Spatial navigation",
    short: "Wayfinding, layouts, mental rotation",
    chc: "Gv",
    onet: ["Spatial Orientation", "Visualization"],
    examples: ["routes without GPS", "room layouts", "maps", "mental rotation"],
    typicalAsk: "how do I get to",
    engages: "hippocampus, entorhinal cortex, retrosplenial cortex (group-average)",
    decayClass: "medium",
    stabilityPrior: STABILITY_BY_CLASS.medium,
    practice: "Look at the map once, put the phone away, and navigate the last ten minutes from memory.",
    lexicon: [
      { term: "directions", weight: 1.5 },
      { term: "route to", weight: 1.3 },
      { term: "the route", weight: 1.1 },
      { term: "fastest route", weight: 1.4 },
      { term: "best route", weight: 1.4 },
      { term: "walking route", weight: 1.4 },
      { term: "driving route", weight: 1.4 },
      { term: "how do i get to", weight: 1.5 },
      { term: "how to get to", weight: 1.5 },
      { term: "map of", weight: 1.2 },
      { term: "the map", weight: 1 },
      { term: "a map", weight: 1 },
      { term: "google maps", weight: 1.3 },
      { term: "apple maps", weight: 1.3 },
      { term: "nearest", weight: 0.9 },
      { term: "navigate", weight: 1.3 },
      { term: "layout", weight: 0.9 },
      { term: "floor plan", weight: 1.3 },
      { term: "spatial", weight: 1 },
      { term: "rotate", weight: 0.7 },
      { term: "north", weight: 0.6 },
      { term: "distance from", weight: 0.9 },
      { term: "which way", weight: 1 },
      { term: "walk from", weight: 1 },
      { term: "drive from", weight: 1 },
      { term: "where is", weight: 0.8 },
    ],
  },
  {
    id: "planning",
    label: "Planning",
    short: "Scheduling, sequencing, decomposing",
    chc: "Executive updating and shifting",
    onet: ["Information Ordering", "Time Sharing"],
    examples: ["study plans", "project breakdowns", "trip itineraries", "sprint plans"],
    typicalAsk: "make me a plan",
    engages: "frontoparietal control network (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Sketch the plan in five lines on paper first, then ask what you missed.",
    lexicon: [
      { term: "plan", weight: 1.3 },
      { term: "schedule", weight: 1.3 },
      { term: "roadmap", weight: 1.3 },
      { term: "timeline", weight: 1 },
      { term: "itinerary", weight: 1.4 },
      { term: "break down", weight: 1.1 },
      { term: "breakdown", weight: 1 },
      { term: "steps to", weight: 1 },
      { term: "step by step", weight: 0.8 },
      { term: "prioritize", weight: 1.2 },
      { term: "prioritise", weight: 1.2 },
      { term: "organize", weight: 1 },
      { term: "organise", weight: 1 },
      { term: "milestones", weight: 1.2 },
      { term: "todo", weight: 0.9 },
      { term: "to-do", weight: 0.9 },
      { term: "checklist", weight: 0.9 },
      { term: "agenda", weight: 1 },
      { term: "sprint", weight: 0.9 },
      { term: "deadline", weight: 0.7 },
      { term: "this week", weight: 0.5 },
      { term: "study plan", weight: 1.5 },
    ],
  },
  {
    id: "ideation",
    label: "Creative ideation",
    short: "Brainstorming, naming, concepts",
    chc: "Gr fluency",
    onet: ["Fluency of Ideas", "Originality"],
    examples: ["project ideas", "names", "titles", "design concepts", "angles for a piece"],
    typicalAsk: "give me ten ideas",
    engages: "default-mode and control network coupling (group-average)",
    decayClass: "medium",
    stabilityPrior: STABILITY_BY_CLASS.medium,
    practice: "List ten of your own before asking; only then ask for ten more and mark which are yours.",
    lexicon: [
      { term: "ideas", weight: 1.5 },
      { term: "idea", weight: 0.9 },
      { term: "brainstorm", weight: 1.6 },
      { term: "suggest", weight: 0.8 },
      { term: "suggestions", weight: 0.9 },
      { term: "names for", weight: 1.4 },
      { term: "name for", weight: 1.3 },
      { term: "title for", weight: 1.3 },
      { term: "titles", weight: 1 },
      { term: "creative", weight: 1 },
      { term: "concept", weight: 0.8 },
      { term: "angles", weight: 0.9 },
      { term: "options for", weight: 0.8 },
      { term: "alternatives", weight: 0.8 },
      { term: "what could i", weight: 0.8 },
      { term: "come up with", weight: 1.2 },
      { term: "pitch", weight: 0.8 },
      { term: "slogan", weight: 1.2 },
      { term: "tagline", weight: 1.2 },
      { term: "theme", weight: 0.6 },
    ],
  },
  {
    id: "implementation",
    label: "Implementation",
    short: "Turning intent into code, formulas, config",
    chc: "Gkn, Grw",
    onet: ["Written Expression", "Information Ordering"],
    examples: ["functions", "scripts", "SQL", "regex", "spreadsheets", "config files"],
    typicalAsk: "write the function",
    engages: "left frontal and parietal regions, weakly specific (group-average)",
    decayClass: "fast",
    stabilityPrior: STABILITY_BY_CLASS.fast,
    practice: "Write the function signature and the first test yourself, then hand over the body.",
    lexicon: [
      { term: "function", weight: 1.2 },
      { term: "code", weight: 1.1 },
      { term: "implement", weight: 1.4 },
      { term: "script", weight: 1.2 },
      { term: "sql", weight: 1.3 },
      { term: "query", weight: 0.8 },
      { term: "regex", weight: 1.4 },
      { term: "class", weight: 0.6 },
      { term: "component", weight: 1 },
      { term: "endpoint", weight: 1.1 },
      { term: "api", weight: 0.7 },
      { term: "python", weight: 1 },
      { term: "javascript", weight: 1 },
      { term: "typescript", weight: 1 },
      { term: "react", weight: 0.9 },
      { term: "bash", weight: 1 },
      { term: "shell", weight: 0.8 },
      { term: "config", weight: 0.9 },
      { term: "yaml", weight: 1 },
      { term: "json", weight: 0.8 },
      { term: "spreadsheet", weight: 0.9 },
      { term: "excel formula", weight: 1.3 },
      { term: "refactor", weight: 1.1 },
      { term: "boilerplate", weight: 1.2 },
      { term: "snippet", weight: 1.1 },
      { term: "css", weight: 1 },
      { term: "html", weight: 0.9 },
      { term: "dockerfile", weight: 1.2 },
      { term: "migration", weight: 0.9 },
      { term: "unit test", weight: 1 },
      { term: "tests for", weight: 1 },
    ],
  },
  {
    id: "verbal",
    label: "Verbal expression",
    short: "Conversation, negotiation, explaining aloud",
    chc: "Gc",
    onet: ["Oral Expression", "Oral Comprehension"],
    examples: ["what to say in a meeting", "a reply to a message", "a toast", "a negotiation"],
    typicalAsk: "what should I say",
    engages: "language plus mentalizing regions (group-average)",
    decayClass: "slow",
    stabilityPrior: STABILITY_BY_CLASS.slow,
    practice: "Say your version out loud once before you ask for a script.",
    lexicon: [
      { term: "what should i say", weight: 1.6 },
      { term: "how do i tell", weight: 1.4 },
      { term: "how to tell", weight: 1.2 },
      { term: "reply to", weight: 1 },
      { term: "respond to", weight: 1 },
      { term: "text back", weight: 1.1 },
      { term: "message to", weight: 0.9 },
      { term: "conversation", weight: 1 },
      { term: "negotiate", weight: 1.3 },
      { term: "negotiation", weight: 1.3 },
      { term: "interview", weight: 0.9 },
      { term: "talk to", weight: 0.8 },
      { term: "speech", weight: 1.1 },
      { term: "toast", weight: 1 },
      { term: "apologize", weight: 1 },
      { term: "apologise", weight: 1 },
      { term: "ask my", weight: 0.8 },
      { term: "politely", weight: 0.9 },
      { term: "small talk", weight: 1.2 },
      { term: "explain to my", weight: 0.9 },
    ],
  },
  {
    id: "attention",
    label: "Sustained attention",
    short: "Deep work blocks, not offloaded but fragmented",
    chc: "Gs",
    onet: ["Selective Attention"],
    examples: ["a 90-minute focus block", "reading without switching"],
    typicalAsk: "(not asked of AI; degraded by switching)",
    engages: "dorsal attention network (group-average)",
    decayClass: "none",
    stabilityPrior: STABILITY_BY_CLASS.none,
    practice: "One 45-minute block with notifications off. Log it as practice.",
    lexicon: [],
  },
];

export const DOMAIN_IDS: DomainId[] = DOMAINS.map((d) => d.id);

export const DOMAIN_BY_ID: Record<DomainId, DomainSpec> = Object.fromEntries(
  DOMAINS.map((d) => [d.id, d]),
) as Record<DomainId, DomainSpec>;

export function domainLabel(id: DomainId): string {
  return DOMAIN_BY_ID[id].label;
}
